name: 'Zigbee Lock (Hyodols)'
packageKey: 'zigbee-lock-hyodols'
permissions:
  zigbee: {}
description: "SmartThings driver for Zigbee lock devices modified by Hyodols"
vendorSupportInformation: "https://support.smartthings.com"
